#注意所有的冒号后边都有个空格 别删别删



#多看阅读 cookie为app里的全部cookie
duokan:
  cookie: 
  
#wps 小程序个人中心账号id 一串数字
wps:
  uid: 123456
  
#橙光游戏app随便抓个包就有token
cg:
  token: 
  skey: 
  
#绅士领域个人uid可抓签到包看到
ssly:
  uid: 12487
  
#时光相册 手机号密码 请抓登陆包查看 手机号里包括区号 86啥的 密码为加密后的密码
everphoto:
  phone: 8611012451110
  password: 

#书香门第 登陆账号密码(只支持字母+数字组合账号)
sxmd:
  account: 
  password: 
  
#uclub这个签到失效了 在cookie里
ucloud:
  token: 
  

#好游快爆 去我的-赚爆米花-任务里 随便抓一个post包 请求数据里有scookie 直接分享商品链接查看  gid 和 key 分享需要兑换的商品链接查看 例https://huodong3.3839.com/n/hykb/bmhstore2/inc/libao/index.php?gid=6237 比如上面这个 gid就是6237  key就是 libao 就是查看inc/后面的那个东西

hykb:
  scookie:  
  gid: 
  key: 

#网易蜗牛读书  都在cookie或者headers里 抓签到包最方便
du163:
  xsrf: 
  X-Auth-Token: 

#吾爱破解 全部cookie
w2pj:
  cookie:
  
# 香网小说网页端 全部cookie
xiang5:
  cookie:  
  
#京东 全部cookie
jd:
  cookie: 

#晋江小说 手机版网页端 m.jjwxc.net cookie中sid 最好抓签到的 填完整 sid=xxx
jjwxc:
  cookie: sid=20070297_1234576798787

#什么值得买网页端 全部cookie
smzdm:
  cookie: 
  
#网易云游戏网页端  请求头里
cg163:
  Authorization:  

#龙空论坛 全部cookie
lkong:
  cookie: 
  
#经管之家 全部cookie
pinggu:
  cookie:  
  
#nga论坛 app端 
nga:
  uid: 
  accesstoken: 

#cdsn 网页 全部cookie
csdn:
  cookie:  
  
#mt论坛 全部cookie
mt:
  cookie:  
  time: ''

#sf轻小说 app
sfacg:
  cookie: 

#猫耳fm 网页 全部cookie
maoer:
  cookie:  
  
  
#爱好论坛 全部cookie
aihao:
  cookie:  
  
#刺猬猫小说 账号密码
hbooker:
  login_name: 
  passwd: 

#ACFun 手机号 密码
acfun:
  phone: 
  password: 

#传奇gm论坛 全部cookie
diygm:
  cookie:  
  
#一亩三分地 登陆账号 密码 (不要设置登录问题) 联众打码平台 账号密码
ym3fd:
  username: 
  password: 
  lzusername: 
  lzpassword: 

#次元狗 全部cookie
acdog:
  cookie:  
  
#登陆联想智选app的手机号密码以及请求头header中的baseinfo
lenovo:
  account: 
  password: 
  baseinfo: 
  
#数码之家全部cookie
mydigit:
  cookie: 
  
#联动云租车 全部cookie
ldygo:
  cookie: 
  
#玩物志好物商店 如果是小程序登陆的 type 默认为wx 如果是网页的就随便改比如 web 123等等,只要不是wx就行,小程序可不填cookie,网页需要
coolbuy:
  type: wx
  authorization: 
  xcsrftoken: 
  cookie:   
  
#阅次元论坛:
abooky:
  cookie: 
  
#富贵论坛
fglt: 
  cookie: 
 
#纪录片之家
jlpzj: 
  cookie: 
  
#ug爱好者
ugsnx:
  cookie:  
  
#好书友论坛 
hsy: 
  cookie: 
  
#togamemod
togamemod: 
  cookie: 
  
#魅族社区
meizu: 
  cookie: 
 
#菜鸟图库
sucai999:
  cookie: 

#埋堆堆app
mdd: 
  appToken: 
  
#闪艺app  都在app请求post数据里  client为ios或者android
shanyi:
  token: 
  u: 
  client: ios
  UA: 
  
  
#香蕉视频 xxx_api_auth记得加双引号
xjvideo:
  xxx_api_auth: 
  baseurl: https://7kp1t2vde8wt7p8tc0km.lagoapps.com
  
    
#有分享论坛
bl20166:
  cookie:        
  
    